import Module from 'manifold-3d';
import type {DesignSettings} from './types';
import {SVGLoader} from 'three/examples/jsm/loaders/SVGLoader.js';
let api:any=null;
export async function initManifold(){if(api)return api;api=await (Module as any)();api.setup();return api;}
function roundedRect(w:number,d:number,r:number,n=24){r=Math.min(Math.max(r,0),Math.min(w,d)/2);const p:any[]=[];for(const [cx,cy,start] of [[w/2-r,d/2-r,0],[-w/2+r,d/2-r,90],[-w/2+r,-d/2+r,180],[w/2-r,-d/2+r,270]])for(let i=0;i<=n;i++){const a=(start+i*90/n)*Math.PI/180;p.push([cx+r*Math.cos(a),cy+r*Math.sin(a)]);}return p;}
export function outline(s:DesignSettings){const {CrossSection}=api,w=s.width,d=s.depth;if(s.shape==='circle')return CrossSection.circle(Math.min(w,d)/2,96);if(s.shape==='square')return CrossSection.square([w,d],true);if(s.shape==='pill')return CrossSection.square([Math.max(.1,w-d),d],true).offset(Math.min(w,d)/2,'Round',2,64);if(s.shape==='bar')return CrossSection.square([w,d],true).offset(Math.min(2.5,d*.1),'Round',2,32);return CrossSection.ofPolygons([roundedRect(w,d,s.cornerRadius)]);}
function mxSocket(s:DesignSettings){const {Manifold}=api,t=s.tolerance;let c=Manifold.cube([14+2*t,14+2*t,s.mxDepth+1],false).translate([0,0,s.baseHeight-s.mxDepth]);for(const [x,y] of [[6.8+t/2,4.7+t/2],[-6.8-t/2,4.7+t/2],[6.8+t/2,-4.7-t/2],[-6.8-t/2,-4.7-t/2]])c=c.add(Manifold.cube([2.6+t,3.2+t,s.mxDepth+1],false).translate([x,y,s.baseHeight-s.mxDepth]));return c.add(Manifold.cube([4.4+2*t,4.4+2*t,s.mxDepth+1],false).translate([0,0,s.baseHeight-s.mxDepth-.1]));}
function keyringCut(s:DesignSettings){const {CrossSection}=api;return CrossSection.circle(5.5,64).subtract(CrossSection.circle(3,64)).translate([s.width/2-7.5,0]);}
function svgCS(svg:string){const {CrossSection}=api;const data=new SVGLoader().parse(svg),polys:any[]=[];for(const path of data.paths)for(const shape of path.toShapes(true)){const pts=shape.extractPoints(48).shape;if(pts.length>=3)polys.push(pts.map((p:any)=>[p.x,-p.y]));}if(!polys.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of polys)for(const [x,y] of p){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}const norm=polys.map(p=>p.map(([x,y])=>[x-(minX+maxX)/2,y-(minY+maxY)/2]));return {cs:CrossSection.evenOdd(norm),w:Math.max(1,maxX-minX),h:Math.max(1,maxY-minY)};}
function artSolid(svg:string,s:DesignSettings){const p=svgCS(svg);if(!p)return null;const scale=Math.min(s.width*.72*s.artworkScale/p.w,s.depth*.58*s.artworkScale/p.h);return p.cs.scale(scale).extrude(Math.max(.15,s.artworkHeight));}
export interface Parts{base:any;cap:any;switchPart:any;full:any;artwork:any|null;stats:any;validation:any;}
export function buildDesign(s:DesignSettings,svg?:string):Parts{const {Manifold}=api;if(s.width<18||s.depth<18)throw Error('Body is too small');const minWall=Math.max(s.wall,s.nozzle*1.5);if(minWall*2>=Math.min(s.width,s.depth))throw Error('Wall thickness is too large');let body=outline(s),base=body.extrude(s.baseHeight).subtract(mxSocket(s));if(s.keyring)base=base.subtract(keyringCut(s).extrude(s.baseHeight+2));const inner=body.offset(-Math.min(minWall*.45,Math.min(s.width,s.depth)/5),'Round',2,32);let cap=inner.extrude(s.capHeight).add(Manifold.cube([4,4,s.stemHeight],false).translate([0,0,-s.stemHeight+s.capHeight-.08]));let artwork:any=null;if(svg&&s.artworkMode!=='flat'){artwork=artSolid(svg,s);if(artwork){const z=s.capHeight-s.artworkHeight*.15;if(s.artworkMode==='raised')cap=cap.add(artwork.translate([0,0,z]));else cap=cap.subtract(artwork.translate([0,0,Math.max(0,s.capHeight-s.artworkHeight+.02)]));}}const sw=Manifold.cube([13.8,13.8,11.5],true).translate([0,0,s.baseHeight+5.75]);const full=base.add(cap.translate([0,0,s.baseHeight])),m=full.getMesh(),bb=full.boundingBox();return{base,cap,switchPart:sw,full,artwork,validation:{manifold:true,wall:minWall,warning:s.tolerance<.2?'Low MX tolerance may fit tightly.':null},stats:{vertices:m.vertProperties.length/m.numProp,triangles:m.triVerts.length/3,volume:full.volume(),size:[bb.max[0]-bb.min[0],bb.max[1]-bb.min[1],bb.max[2]-bb.min[2]]}};}
export function manifoldToThree(mesh:any,THREE:any){const m=mesh.getMesh(),stride=m.numProp,pos=new Float32Array(m.vertProperties.length/stride*3);for(let i=0,v=0;i<m.vertProperties.length;i+=stride,v+=3){pos[v]=m.vertProperties[i];pos[v+1]=m.vertProperties[i+1];pos[v+2]=m.vertProperties[i+2];}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setIndex(new THREE.BufferAttribute(new Uint32Array(m.triVerts),1));g.computeVertexNormals();return g;}