import Module from 'manifold-3d';
import type {DesignSettings} from './types';
import {SVGLoader} from 'three/examples/jsm/loaders/SVGLoader.js';

let api:any=null;
export async function initManifold(){if(api)return api;api=await (Module as any)();api.setup();return api;}
function roundedRect(w:number,d:number,r:number,n=24){r=Math.min(Math.max(r,0),Math.min(w,d)/2);const p:any[]=[];for(const [cx,cy,start] of [[w/2-r,d/2-r,0],[-w/2+r,d/2-r,90],[-w/2+r,-d/2+r,180],[w/2-r,-d/2+r,270]])for(let i=0;i<=n;i++){const a=(start+i*90/n)*Math.PI/180;p.push([cx+r*Math.cos(a),cy+r*Math.sin(a)])}return p}
export function outline(s:DesignSettings){const {CrossSection}=api,w=s.width,d=s.depth;if(s.shape==='circle')return CrossSection.circle(Math.min(w,d)/2,96);if(s.shape==='square')return CrossSection.square([w,d],true);if(s.shape==='pill')return CrossSection.square([Math.max(.1,w-d),d],true).offset(Math.min(w,d)/2,'Round',2,64);if(s.shape==='bar')return CrossSection.square([w,d],true).offset(Math.min(2.5,d*.1),'Round',2,32);return CrossSection.ofPolygons([roundedRect(w,d,s.cornerRadius)])}
function switchPlacements(s:DesignSettings){const n=Math.max(1,Math.min(3,Math.round(s.switchCount||1)));if(n===1)return [[0,0]];const spacing=Math.max(12,Math.min(s.width-16,s.switchSpacing||18));if(n===2)return [[-spacing/2,0],[spacing/2,0]];return [[-spacing,0],[0,0],[spacing,0]]}
function mxSocket(s:DesignSettings){const {Manifold}=api,t=Math.max(.05,s.tolerance),depth=Math.min(s.mxDepth+.35,s.baseHeight-.35);let all:any=null;for(const [ox,oy] of switchPlacements(s)){let c=Manifold.cube([14+2*t,14+2*t,depth],false).translate([ox,oy,s.baseHeight-depth]);for(const [x,y] of [[7.05+t/2,4.8+t/2],[7.05+t/2,-4.8-t/2],[-7.05-t/2,4.8+t/2],[-7.05-t/2,-4.8-t/2]])c=c.add(Manifold.cube([2.7+t,3+t,depth],false).translate([ox+x,oy+y,s.baseHeight-depth]));all=all?all.add(c):c}return all}
function parsedSvg(svg:string,s:DesignSettings){const data=new SVGLoader().parse(svg),groups=new Map<string,any[]>();let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const path of data.paths){const color=String((path as any).userData?.style?.fill||path.color?.getStyle?.()||s.artworkColor).toUpperCase();for(const shape of path.toShapes(true)){const pts=shape.extractPoints(48),rings=[pts.shape,...(pts.holes||[])];for(const ring of rings)if(ring.length>=3){const poly=ring.map((p:any)=>[p.x,-p.y]);for(const [x,y] of poly){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(!groups.has(color))groups.set(color,[]);groups.get(color)!.push(poly)}}}if(!groups.size||!isFinite(minX))return null;const cx=(minX+maxX)/2,cy=(minY+maxY)/2;const naturalW=Math.max(1,maxX-minX),naturalH=Math.max(1,maxY-minY);const target=Math.max(20,Math.min(90,s.width));const scale=target/Math.max(naturalW,naturalH)*Math.max(.25,s.artworkScale/.78);const mapped=new Map<string,any[]>();for(const [color,polys] of groups)mapped.set(color,polys.map(p=>p.map(([x,y]:number[])=>[(x-cx)*scale,(y-cy)*scale])));return {groups:mapped}}
function artSection(svg:string,s:DesignSettings){const p=parsedSvg(svg,s);if(!p)return null;let u:any=null;for(const polys of p.groups.values()){const cs=api.CrossSection.ofPolygons(polys);u=u?u.add(cs):cs}return u}
function requiredShell(svg:string,s:DesignSettings){let art=artSection(svg,s);if(!art)return outline(s);const keep=Math.max(17.2,14+2*s.tolerance+2*Math.max(1.2,s.wall));for(const [x,y] of switchPlacements(s)){const k=api.CrossSection.square([keep,keep],true).offset(2.2,'Round',2,32).translate([x,y]);art=art.add(k)}return art}
function svgParts(svg:string,s:DesignSettings){const p=parsedSvg(svg,s);if(!p)return [];const out:any[]=[];for(const [color,polys] of p.groups){const cs=api.CrossSection.ofPolygons(polys);const h=s.artworkMode==='flat'?Math.max(.16,Math.min(.3,s.artworkHeight)):Math.max(.18,s.artworkHeight);const z=s.capHeight-(s.artworkMode==='raised'?.02:s.artworkMode==='flat'?Math.min(.08,h):h);out.push({mesh:cs.extrude(h).translate([0,0,Math.max(.02,z)]),color})}return out}
function unionArtwork(parts:any[]){if(!parts.length)return null;let u=parts[0].mesh;for(let i=1;i<parts.length;i++)u=u.add(parts[i].mesh);return u}
function switchPreview(){const {Manifold}=api;let sw=Manifold.cube([13.8,13.8,5.4],true).translate([0,0,-2.7]);sw=sw.add(Manifold.cube([12,12,3],true).translate([0,0,1.2]));sw=sw.add(Manifold.cube([4.2,1.1,4],true).translate([0,0,4.1])).add(Manifold.cube([1.1,4.2,4],true).translate([0,0,4.1]));return sw}
export interface Parts{base:any;cap:any;switchPart:any;switchPlacements:number[][];full:any;artwork:any|null;artworkParts:{mesh:any;color:string}[];artworkMode:DesignSettings['artworkMode'];stats:any;validation:any;}
export function buildDesign(s:DesignSettings,svg?:string):Parts{const {Manifold}=api;if(s.width<18)throw Error('Design size is too small');if(s.capHeight<1.2)throw Error('Cap is too thin');const core=svg?requiredShell(svg,s):outline(s);const outer=core.offset(Math.max(2.2,s.wall+1),'Round',2,48);const capOutline=core.offset(Math.max(.7,s.wall*.45),'Round',2,48);let base=outer.extrude(s.baseHeight).subtract(mxSocket(s));let cap=capOutline.extrude(s.capHeight);const placements=switchPlacements(s);let artwork:any=null,artworkParts:{mesh:any,color:string}[]=[];if(svg){artworkParts=svgParts(svg,s);if(s.artworkMode==='engraved'){const cut=unionArtwork(artworkParts);if(cut)cap=cap.subtract(cut);artworkParts=[]}else artwork=unionArtwork(artworkParts)}for(const [ox,oy] of placements)cap=cap.add(Manifold.cube([4.15,4.15,s.stemHeight],true).translate([ox,oy,-s.stemHeight/2+.03]));let full=base.add(cap.translate([0,0,s.baseHeight]));if(artwork)full=full.add(artwork.translate([0,0,s.baseHeight]));const m=full.getMesh(),bb=full.boundingBox();return {base,cap,switchPart:switchPreview(),switchPlacements:placements,full,artwork,artworkParts,artworkMode:s.artworkMode,validation:{manifold:true,wall:s.wall,warning:null},stats:{vertices:m.vertProperties.length/m.numProp,triangles:m.triVerts.length/3,volume:full.volume(),size:[bb.max[0]-bb.min[0],bb.max[1]-bb.min[1],bb.max[2]-bb.min[2]]}}}
export function manifoldToThree(mesh:any,THREE:any){const m=mesh.getMesh(),stride=m.numProp,pos=new Float32Array(m.vertProperties.length/stride*3);for(let i=0,v=0;i<m.vertProperties.length;i+=stride,v+=3){pos[v]=m.vertProperties[i];pos[v+1]=m.vertProperties[i+1];pos[v+2]=m.vertProperties[i+2]}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setIndex(new THREE.BufferAttribute(new Uint32Array(m.triVerts),1));g.computeVertexNormals();return g}
