import Module from 'manifold-3d';
import type {DesignSettings} from './types';
import {SVGLoader} from 'three/examples/jsm/loaders/SVGLoader.js';

let api:any=null;
export async function initManifold(){if(api)return api;api=await (Module as any)();api.setup();return api;}

type Ring=number[][];
type ParsedShape={color:string;outer:Ring;holes:Ring[]};
function roundedRect(w:number,d:number,r:number,n=20){r=Math.min(Math.max(r,0),Math.min(w,d)/2);const p:any[]=[];for(const [cx,cy,start] of [[w/2-r,d/2-r,0],[-w/2+r,d/2-r,90],[-w/2+r,-d/2+r,180],[w/2-r,-d/2+r,270]])for(let i=0;i<=n;i++){const a=(start+i*90/n)*Math.PI/180;p.push([cx+r*Math.cos(a),cy+r*Math.sin(a)])}return p}
export function outline(s:DesignSettings){const {CrossSection}=api,w=s.width,d=s.depth;if(s.shape==='circle')return CrossSection.circle(Math.min(w,d)/2,96);if(s.shape==='square')return CrossSection.square([w,d],true);if(s.shape==='pill')return CrossSection.square([Math.max(.1,w-d),d],true).offset(Math.min(w,d)/2,'Round',2,48);if(s.shape==='bar')return CrossSection.square([w,d],true).offset(Math.min(2.5,d*.1),'Round',2,32);return CrossSection.ofPolygons([roundedRect(w,d,s.cornerRadius)])}
function switchPlacements(s:DesignSettings){const n=Math.max(1,Math.min(3,Math.round(s.switchCount||1)));if(n===1)return [[0,0]];const spacing=Math.max(16,Math.min(Math.max(16,s.width-18),s.switchSpacing||18));if(n===2)return [[-spacing/2,0],[spacing/2,0]];return [[-spacing,0],[0,0],[spacing,0]]}
function section(poly:Ring){return api.CrossSection.ofPolygons([poly])}
function parsedSvg(svg:string,s:DesignSettings){const data=new SVGLoader().parse(svg);const raw:{color:string;outer:Ring;holes:Ring[]}[]=[];let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const path of data.paths){const color=String((path as any).userData?.style?.fill||path.color?.getStyle?.()||s.artworkColor).toUpperCase();for(const shape of path.toShapes(true)){const pts=shape.extractPoints(32);if(pts.shape.length<3)continue;const cv=(ring:any[])=>ring.map((p:any)=>[p.x,-p.y]);const outer=cv(pts.shape),holes=(pts.holes||[]).filter((h:any[])=>h.length>=3).map(cv);for(const [x,y] of outer){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}raw.push({color,outer,holes})}}if(!raw.length||!isFinite(minX))return null;const cx=(minX+maxX)/2,cy=(minY+maxY)/2,nw=Math.max(.001,maxX-minX),nh=Math.max(.001,maxY-minY);const target=Math.max(20,Math.min(90,s.width))*Math.max(.35,s.artworkScale/.78);const k=target/Math.max(nw,nh);const map=(r:Ring)=>r.map(([x,y])=>[(x-cx)*k,(y-cy)*k]);return raw.map(x=>({color:x.color,outer:map(x.outer),holes:x.holes.map(map)})) as ParsedShape[]}
function shapeSection(x:ParsedShape){let cs=section(x.outer);for(const h of x.holes)cs=cs.subtract(section(h));return cs}
function artworkUnion(parsed:ParsedShape[]){let u:any=null;for(const x of parsed){const cs=shapeSection(x);u=u?u.add(cs):cs}return u}
function silhouette(parsed:ParsedShape[]){let u:any=null;for(const x of parsed){const cs=section(x.outer);u=u?u.add(cs):cs}if(!u)return null;const smooth=2.2;try{u=u.offset(smooth,'Round',2,24).offset(-smooth,'Round',2,24)}catch{}return u}
function ensureSwitchCoverage(plate:any,s:DesignSettings){const clear=Math.max(17.5,14+2*s.tolerance+2.2);let out=plate;for(const [x,y] of switchPlacements(s)){const guard=api.CrossSection.square([clear-4,clear-4],true).offset(2,'Round',2,24).translate([x,y]);const missing=guard.subtract(out);if(!missing.isEmpty?.())out=out.add(guard)}return out}
function mxSocket(s:DesignSettings){const {Manifold}=api,t=Math.max(.05,s.tolerance),depth=Math.min(s.mxDepth,s.baseHeight-.6);let all:any=null;for(const [ox,oy] of switchPlacements(s)){let c=Manifold.cube([14+2*t,14+2*t,depth],false).translate([ox-7-t,oy-7-t,s.baseHeight-depth]);for(const [x,y] of [[-7.2,-4.8],[-7.2,1.8],[5.0,-4.8],[5.0,1.8]])c=c.add(Manifold.cube([2.2,3,depth],false).translate([ox+x,oy+y,s.baseHeight-depth]));all=all?all.add(c):c}return all}
function svgParts(parsed:ParsedShape[],s:DesignSettings){const grouped=new Map<string,any>();for(const x of parsed){const cs=shapeSection(x),old=grouped.get(x.color);grouped.set(x.color,old?old.add(cs):cs)}const out:any[]=[];for(const [color,cs] of grouped){const h=s.artworkMode==='flat'?Math.max(.18,Math.min(.3,s.artworkHeight)):Math.max(.22,s.artworkHeight);const z=s.artworkMode==='raised'?s.capHeight-.02:s.artworkMode==='flat'?s.capHeight-h:s.capHeight-h;out.push({mesh:cs.extrude(h).translate([0,0,Math.max(.02,z)]),color})}return out}
function unionArtwork(parts:any[]){if(!parts.length)return null;let u=parts[0].mesh;for(let i=1;i<parts.length;i++)u=u.add(parts[i].mesh);return u}
function switchPreview(){const {Manifold}=api;let sw=Manifold.cube([13.9,13.9,5.2],true).translate([0,0,-2.6]);sw=sw.add(Manifold.cube([12.1,12.1,2.8],true).translate([0,0,1.25]));sw=sw.add(Manifold.cube([4.1,1.15,3.6],true).translate([0,0,3.9])).add(Manifold.cube([1.15,4.1,3.6],true).translate([0,0,3.9]));return sw}
export interface Parts{base:any;cap:any;switchPart:any;switchPlacements:number[][];full:any;artwork:any|null;artworkParts:{mesh:any;color:string}[];artworkMode:DesignSettings['artworkMode'];stats:any;validation:any;}
export function buildDesign(s:DesignSettings,svg?:string):Parts{const {Manifold}=api;if(s.width<18)throw Error('Design size is too small');if(s.capHeight<1.2)throw Error('Cap is too thin');const parsed=svg?parsedSvg(svg,s):null;let plate=parsed?silhouette(parsed):outline(s);if(!plate)plate=outline(s);plate=ensureSwitchCoverage(plate,s);const tol=Math.max(.12,s.capClearance),border=Math.max(1.6,s.wall);const well=plate.offset(tol,'Round',2,32);const outer=well.offset(border,'Round',2,32);const bodyTop=s.baseHeight+Math.max(.8,s.capHeight*.55);let base=outer.extrude(bodyTop);const wellCut=well.extrude(s.capHeight+1.2).translate([0,0,s.baseHeight-.25]);base=base.subtract(wellCut).subtract(mxSocket(s));let cap=plate.extrude(s.capHeight);const placements=switchPlacements(s);for(const [ox,oy] of placements){const stem=Manifold.cube([4.15,4.15,s.stemHeight],true).translate([ox,oy,-s.stemHeight/2+.04]);cap=cap.add(stem)}let artwork:any=null,artworkParts:{mesh:any,color:string}[]=[];if(parsed){artworkParts=svgParts(parsed,s);if(s.artworkMode==='engraved'){const cut=unionArtwork(artworkParts);if(cut)cap=cap.subtract(cut);artworkParts=[]}else artwork=unionArtwork(artworkParts)}let full=base.add(cap.translate([0,0,s.baseHeight]));if(artwork)full=full.add(artwork.translate([0,0,s.baseHeight]));const m=full.getMesh(),bb=full.boundingBox();const warning=s.capClearance<.15?'Cap clearance is tight; test fit recommended.':null;return {base,cap,switchPart:switchPreview(),switchPlacements:placements,full,artwork,artworkParts,artworkMode:s.artworkMode,validation:{manifold:true,wall:s.wall,warning},stats:{vertices:m.vertProperties.length/m.numProp,triangles:m.triVerts.length/3,volume:full.volume(),size:[bb.max[0]-bb.min[0],bb.max[1]-bb.min[1],bb.max[2]-bb.min[2]]}}}
export function manifoldToThree(mesh:any,THREE:any){const m=mesh.getMesh(),stride=m.numProp,pos=new Float32Array(m.vertProperties.length/stride*3);for(let i=0,v=0;i<m.vertProperties.length;i+=stride,v+=3){pos[v]=m.vertProperties[i];pos[v+1]=m.vertProperties[i+1];pos[v+2]=m.vertProperties[i+2]}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setIndex(new THREE.BufferAttribute(new Uint32Array(m.triVerts),1));g.computeVertexNormals();return g}
